market/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<category_slug>[\w-]+)/(?P<product_id>\d+)_(?P<product_slug>[\w-]+)/$', views.product_details,
        name='details'),
    url(r'^(?P<category_slug>[\w-]+)/$', views.product_list, name='list'),
    url(r'', views.product_list_homepage, name='homepage'),
]

yulaimusin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'', include('market.urls', namespace='market')),
]

market/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Модель категории
class Category(models.Model):
    title = models.CharField(max_length=50, db_index=True, verbose_name='Заголовок')
    slug = models.SlugField(db_index=True, unique=True, verbose_name='ЧПУ категории')

    class Meta:
        ordering = ['title']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

    def get_category_url(self):
        return reverse('market:list', kwargs={'category_slug': self.slug})


# Модель продукта
class Product(models.Model):
    title = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    category = models.ForeignKey(Category, verbose_name='Категория')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='ЧПУ товара')
    image = models.ImageField(upload_to='products/%m.%Y/', blank=True, verbose_name='Изображение')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    in_stock = models.IntegerField(default=0, db_index=True, verbose_name='Кол-во в наличии')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Товар добавлен')
    updated = models.DateTimeField(auto_now=True, verbose_name='Товар обновлен')

    class Meta:
        ordering = ['id']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = [['id', 'slug']]

    def __str__(self):
        return self.title

    def get_product_url(self):
        return reverse('market:details', kwargs={'category_slug': self.category.slug, 'product_id': self.id,
                                                 'product_slug': self.slug})

market/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Category, Product


def product_list_homepage(request):
    categories = Category.objects.all()
    products = Product.objects.filter(in_stock__gt=0)
    context = {"categories": categories, "products": products}
    return render(request, "market/product_list_homepage.html", context=context)


def product_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category, in_stock__gt=0)
    context = {"category": category, "products": products}
    return render(request, "market/product_list.html", context=context)


def product_details(request, category_slug=None, product_id=None, product_slug=None):
    product = get_object_or_404(Product, id=product_id)
    if product.category.slug != category_slug or product.slug != product_slug:
        raise Http404
    context = {"product": product}
    return render(request, "market/product_details.html", context=context)

market/templates/market/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Каталог умных телефонов{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/narrow-jumbotron.css" %}" rel="stylesheet">
    <link href="{% static "css/album.css" %}" rel="stylesheet">
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url "market:homepage" %}">Каталог умных телефонов</a>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="/telefony-samsung/">Телефоны Samsung</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/telefony-apple/">Телефоны Apple</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>

      {% block jumbotron %}
      <div class="jumbotron">
        <h1 class="display-3">Каталог умных телефонов</h1>
        <p class="lead">Самые умные телефоны Samsung и Apple вы можете приобрести у нас на лучших условиях!</p>
      </div>
      {% endblock jumbotron %}

      <div class="marketing">
        {% block content %}{% endblock content %}
      </div>

      <footer class="footer">
        <p>&copy; Каталог умных телефонов 2017</p>
      </footer>

    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
  </body>
</html>

market/templates/market/product_details.html
{% extends "market/base.html" %}

{% block title %}{{ product.title }} | {{ block.super }}{% endblock title %}
{% block jumbotron %} {% endblock jumbotron %}

{% block content %}
    <h1><a href="{{ product.get_product_url }}">{{ product.title }}</a></h1>
    <p>Категория: <a href="{{ product.category.get_category_url }}">{{ product.category }}</a></p>
    <p><img src="{{ product.image.url }}" style="width: 100%; display: block;"></p>
    <p>{{ product.description }}</p>
    <p>Цена: {{ product.price }} руб.</p>
    {% if product.in_stock > 0 %}
        <p>В наличии: {{ product.in_stock }} шт.</p>
    {% else %}
        <p>Нет в наличии</p>
    {% endif %}
{% endblock content %}

market/templates/market/product_list.html
{% extends "market/base.html" %}

{% block title %}{{ category.title }} | {{ block.super }}{% endblock title %}
{% block jumbotron %} {% endblock jumbotron %}

{% block content %}
    {% for product in products %}
    <div class="card">
        <h2><a href="{{ product.get_product_url }}">{{ product.title }}</a></h2>
        <p><img src="{{ product.image.url }}" style="width: 100%; display: block;"></p>
        <p class="card-text">{{ product.description }}</p>
        <p>Цена: {{ product.price }} руб.</p>
    </div>
    {% endfor %}
{% endblock content %}

market/templates/market/product_list_homepage.html
{% extends "market/base.html" %}

{% block title %}{{ block.super }}{% endblock title %}
{% block jumbotron %}{{ block.super }}{% endblock jumbotron %}

{% block content %}
    {% for product in products %}
    <div class="card">
        <h2><a href="{{ product.get_product_url }}">{{ product.title }}</a></h2>
        <p>Категория: <a href="{{ product.category.get_category_url }}">{{ product.category }}</a></p>
        <p><img src="{{ product.image.url }}" style="width: 100%; display: block;"></p>
        <p class="card-text">{{ product.description }}</p>
        <p>Цена: {{ product.price }} руб.</p>
    </div>
    {% endfor %}
{% endblock content %}